// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvVeeeSggeCcrJ6OZ4wF1s1p0NguQjk4',
    appId: '1:559609315689:web:c4439e42b9b93dc0487df8',
    messagingSenderId: '559609315689',
    projectId: 'todo-app-route-9246d',
    authDomain: 'todo-app-route-9246d.firebaseapp.com',
    storageBucket: 'todo-app-route-9246d.appspot.com',
    measurementId: 'G-N3WKPYQ8RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGlyAIzgEiv9SV_7e0kl_BKVnjoP9X3E',
    appId: '1:559609315689:android:944b23690df2cd96487df8',
    messagingSenderId: '559609315689',
    projectId: 'todo-app-route-9246d',
    storageBucket: 'todo-app-route-9246d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJeUKL-OlPH73YV341EzqtTXQDAZ-95mA',
    appId: '1:559609315689:ios:f99d84ae567cd27e487df8',
    messagingSenderId: '559609315689',
    projectId: 'todo-app-route-9246d',
    storageBucket: 'todo-app-route-9246d.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJeUKL-OlPH73YV341EzqtTXQDAZ-95mA',
    appId: '1:559609315689:ios:f99d84ae567cd27e487df8',
    messagingSenderId: '559609315689',
    projectId: 'todo-app-route-9246d',
    storageBucket: 'todo-app-route-9246d.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVvVeeeSggeCcrJ6OZ4wF1s1p0NguQjk4',
    appId: '1:559609315689:web:e5d0cdb4ab544351487df8',
    messagingSenderId: '559609315689',
    projectId: 'todo-app-route-9246d',
    authDomain: 'todo-app-route-9246d.firebaseapp.com',
    storageBucket: 'todo-app-route-9246d.appspot.com',
    measurementId: 'G-2LZTGRQDNR',
  );

}